--- Logging error ---
Traceback (most recent call last):
  File "c:\users\61574\appdata\local\programs\python\python38\lib\logging\handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "c:\users\61574\appdata\local\programs\python\python38\lib\logging\handlers.py", line 185, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\logging\__init__.py", line 671, in format
    s = self.formatMessage(record)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\formatter.py", line 131, in formatMessage
    escapes = self._escape_code_map(record.levelname)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\formatter.py", line 144, in _escape_code_map
    codes.setdefault("log_color", self._get_escape_code(self.log_colors, item))
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\formatter.py", line 167, in _get_escape_code
    return colorlog.escape_codes.parse_colors(log_colors.get(item, ""))
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\escape_codes.py", line 104, in parse_colors
    return "".join(escape_codes[n] for n in string.split(",") if n)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\escape_codes.py", line 104, in <genexpr>
    return "".join(escape_codes[n] for n in string.split(",") if n)
KeyError: "'green'"
Call stack:
  File "c:\users\61574\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\61574\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\61574\AppData\Local\Programs\Python\Python38\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\config\__init__.py", line 189, in console_main
    code = main()
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\config\__init__.py", line 166, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 114, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\qkex20230901\qkexapifu\test_fu.py", line 114, in test_follow_user_traders
    logger.info('查询跟单用户的交易员信息返回信息：{%s}' % response.json())
  File "C:\qkex20230901\logutil.py", line 96, in info
    self.__console('info', message)
  File "C:\qkex20230901\logutil.py", line 78, in __console
    self.logger.info(message)
Message: "查询跟单用户的交易员信息返回信息：{{'code': '0', 'data': [], 'ts': 1695112128559}}"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\61574\appdata\local\programs\python\python38\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\logging\__init__.py", line 671, in format
    s = self.formatMessage(record)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\formatter.py", line 131, in formatMessage
    escapes = self._escape_code_map(record.levelname)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\formatter.py", line 144, in _escape_code_map
    codes.setdefault("log_color", self._get_escape_code(self.log_colors, item))
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\formatter.py", line 167, in _get_escape_code
    return colorlog.escape_codes.parse_colors(log_colors.get(item, ""))
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\escape_codes.py", line 104, in parse_colors
    return "".join(escape_codes[n] for n in string.split(",") if n)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\colorlog\escape_codes.py", line 104, in <genexpr>
    return "".join(escape_codes[n] for n in string.split(",") if n)
KeyError: "'green'"
Call stack:
  File "c:\users\61574\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\61574\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\61574\AppData\Local\Programs\Python\Python38\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\config\__init__.py", line 189, in console_main
    code = main()
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\config\__init__.py", line 166, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 324, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\main.py", line 349, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 114, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\python.py", line 1788, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\61574\appdata\local\programs\python\python38\lib\site-packages\_pytest\python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\qkex20230901\qkexapifu\test_fu.py", line 114, in test_follow_user_traders
    logger.info('查询跟单用户的交易员信息返回信息：{%s}' % response.json())
  File "C:\qkex20230901\logutil.py", line 96, in info
    self.__console('info', message)
  File "C:\qkex20230901\logutil.py", line 78, in __console
    self.logger.info(message)
Message: "查询跟单用户的交易员信息返回信息：{{'code': '0', 'data': [], 'ts': 1695112128559}}"
Arguments: ()
